-- AlterTable
ALTER TABLE `Invoice` MODIFY `taxRate` DECIMAL(5, 2) NOT NULL DEFAULT 20,
    MODIFY `subtotal` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    MODIFY `taxAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    MODIFY `total` DECIMAL(12, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `InvoiceItem` MODIFY `unitPrice` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    MODIFY `lineTotal` DECIMAL(12, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `LabService` MODIFY `unitPrice` DECIMAL(12, 2) NOT NULL DEFAULT 0;

